### ISSUE TITLE
please help me to debugg this small project

### ISSUE THREAD

**Issue by Hedayatullahnikzad** [hamidafghan/laravel-class#8]
@hamidafghan 
what is exatly $post it fetch data from post,tag and comment tables.
#8 I marked my problems inside ** **.
@section('content')
    <div class="container mx-auto">
        <div class="shadow-lg w-full bg-white rounded p-5">
            <p class="text-gray-800 py-3 text-lg font-semibold">{{$post->title}} <span
                        class="text-sm text-gray-600 font-normal">By 

> 

> 

> 

> {{$post->user->name}} 

> on {{ $post->created_at }}</span>

            </p>
            <p class="text-gray-700  ">{{**$post->body}**}</p>

            <p class="my-5">

                @foreach**($post->tags as $tag)**
                    <span class="text-gray-600 font-semibold px-2 py-1 rounded-full bg-gray-200 px-2">#{{ 

> $tag->name }}</span>

                @endforeach
            </p>
        </div>

        <div class="px-10 my-10">

            @foreach**($post->comments as $comment**)
                <div class="bg-white p-5 rounded border shadow-xl my-2">
                    <p class="text-gray-600 text-sm">{{ $comment->created_at }}</p>
                    <p class="text-base text-gray-800">{{ $comment->comment }}</p>
                </div>
            @endforeach

        </div>
    </div>
@stop

**Comment by hamidafghan** [comment]
Thank you for creating issues

1.@foreach**($post->tags as $tag)**
   We find the post by id in controller then send that in view via `compact` function,
   about the word `tages` we have it as function on `Post` model. 
2. @foreach**($post->tags as $tag)**
   So a post may have one or some tage that we can foreach them to display
3. @foreach**($post->comments as $comment**)
   for sure we for a post we can have one or many comment, so we get the comments via `comment` function and then foreach that to display.

**Comment by hamidafghan** [comment]
@Hedayatullahnikzad If it looks the nice answer to you, so you can close the issue. 
Many thanks.
